### PR TITLE
release/v1.0.1

### PR DESCRIPTION
**Pull request by CiaranOMara**
This pull request contains general housekeeping. There are no code changes, just CI and documentation updates. Please let me know if I've missed something, if something doesn't make sense, or whether there are better CI implementations.

### CODE REVIEW

**Comment by CiaranOMara** [comment]
Probably worth waiting for https://github.com/BioJulia/Libz.jl/pull/66 to be released so that it can be added to the compat section here.

**Comment by CiaranOMara** [comment]
I like the idea of separating documentation builds from code tests. Let's set up that workflow before merging. I've also got some compatibility tests running over at CiaranOMara/GenomicFeatures.jl, I'd like to add those results to this release as well.

**Comment by BenJWard** [comment]
Yeah the Compat helper looks cool, I made a mental note to set it up for our genome assembler repository.

**Comment by CiaranOMara** [comment]
I think this is now good enough. However, the `DOCUMENTER_KEY` would need to be set up before merging this into master.

**Comment by CiaranOMara** [comment]
I set the CompatHelper to generate PRs against the `master` branch with the gitflow workflow in mind. The idea being that development should not block compatibility changes or hotfixes.

**Comment by CiaranOMara** [comment]
@BenJWard, bump re `DOCUMENTER_KEY`.

**Comment by CiaranOMara** [comment]
@BenJWard, I'm happy for you to merge this into master as well as cut the release, and I think you're spot on about v1 patches going to general. 

Also, the documenter key looks good, it was able to generate the [PR preview](https://biojulia.net/GenomicFeatures.jl/previews/PR22/).

**Pull request merged**
